spring:
  application:
    name: docker-example

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9001
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
    prometheus:
      enabled: true
    metrics:
      enabled: true
  jmx:
    metrics:
      export:
        enabled: false
  prometheus:
    metrics:
      export:
        enabled: true